-- +goose Up

CREATE TABLE accounts (
    id         BIGINT      NOT NULL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  accounts            IS 'source of truth for account information';
COMMENT ON COLUMN accounts.id         IS 'unique identified chosen by user';
COMMENT ON COLUMN accounts.created_at IS 'example of account information; populated by database - DO NOT supply value when inserting';

CREATE TABLE events (
    id         UUID        NOT NULL DEFAULT gen_random_uuid () PRIMARY KEY,
    type       TEXT        NOT NULL,
    payload    JSONB       NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  events            IS 'append-only table. represents all state changes received by the system.';
COMMENT ON COLUMN events.id         IS 'unique identifier; generated by the database - DO NOT supply a value when inserting';
COMMENT ON COLUMN events.type       IS 'describes what type of event this is';
COMMENT ON COLUMN events.payload    IS 'raw JSON payload that contains information about the event';
COMMENT ON COLUMN events.created_at IS 'exact timestamp that event was received by the system; generated by the database - DO NOT supply a value when inserting';

CREATE TABLE ledger_entries (
    id           BIGSERIAL      NOT NULL PRIMARY KEY,
    account_id   BIGINT         NOT NULL REFERENCES accounts (id),
    amount_micro BIGINT         NOT NULL,
    event_id     UUID           NOT NULL REFERENCES events (id),
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  ledger_entries              IS 'append-only table. records all changes to account balances';
COMMENT ON COLUMN ledger_entries.id           IS 'auto-increment id to identify changes to user balances';
COMMENT ON COLUMN ledger_entries.account_id   IS 'which account''s balance is beign changed';
COMMENT ON COLUMN ledger_entries.amount_micro IS 'represents how much the balance is change by in micro-units, where 1 unit = 1,000,000 micro-units';
COMMENT ON COLUMN ledger_entries.event_id     IS 'the event which caused the account''s balance to change';
COMMENT ON COLUMN ledger_entries.created_at   IS 'exact timestamp that balance change occurred; generated by the database - DO NOT supply a value when inserting';
