// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// source of truth for account information
type Account struct {
	// unique identified chosen by user
	ID int64 `json:"id"`
	// example of account information; populated by database - DO NOT supply value when inserting
	CreatedAt time.Time `json:"created_at"`
}

// append-only table. represents all state changes received by the system.
type Event struct {
	// unique identifier; generated by the database - DO NOT supply a value when inserting
	ID pgtype.UUID `json:"id"`
	// describes what type of event this is
	Type string `json:"type"`
	// raw JSON payload that contains information about the event
	Payload []byte `json:"payload"`
	// exact timestamp that event was received by the system; generated by the database - DO NOT supply a value when inserting
	CreatedAt time.Time `json:"created_at"`
}

// append-only table. records all changes to account balances
type LedgerEntry struct {
	// auto-increment id to identify changes to user balances
	ID int64 `json:"id"`
	// which account's balance is beign changed
	AccountID int64 `json:"account_id"`
	// represents how much the balance is change by in micro-units, where 1 unit = 1,000,000 micro-units
	AmountMicro int64 `json:"amount_micro"`
	// the event which caused the account's balance to change
	EventID pgtype.UUID `json:"event_id"`
	// exact timestamp that balance change occurred; generated by the database - DO NOT supply a value when inserting
	CreatedAt time.Time `json:"created_at"`
}
